# Generated by Django 3.2 on 2021-04-21 17:02

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('price_previous', models.IntegerField()),
                ('on_sale', models.BooleanField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(check=models.Q(on_sale=django.db.models.expressions.ExpressionWrapper(models.Q(price__lt=django.db.models.expressions.F('price_previous')), output_field=models.BooleanField())), name='on_sale_check'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(check=models.Q(price__lte=django.db.models.expressions.F('price_previous')), name='price_lte_price_previous'),
        ),
    ]
